### ISSUE TITLE
Toggling multiple checkboxes

### ISSUE THREAD

**Issue by grks** [davidkpiano/react-redux-form#1061]
Hi,

I'm struggling a bit with how to toggle an array of checkboxes in a good way using a LocalForm. I have done it so that I'm updating the state of the form in onUpdate and mapping this.state to initialState props on the LocalForm. Then I setup the checkbox controls with a model of "types[]".

What I want to do is to have a Select All / Select None checkbox that should toggle all checkbox in another group, but I don't get how this is supposed to be done as there seems to be so many different options.

So I wonder what action creator is suitable for this? Is it toggle, xor, change, remove or maybe use map or filter? Or should I just update the state directly and not go via the action creators as it's a LocalForm?

have tried to wrap my head around it, gone up and down in the docs and other issues, but don't really get it so I would really appreciate a push in the right direction or maybe some example that does something similar, as I would really like to use react-redux-form for a project.

Thanks!

**Comment by davidkpiano** [comment]
Please provide some starter code so we can work off of that. The links are in the issue template.

**Comment by grks** [comment]
Hi David!

I know this example is not going to work as it's not updating the state properly and that it's something I don't understand yet about react-redux-form. But the example should show what part I have failed to grasp with react-redux-form and how to update state for a LocalForm: https://codepen.io/anon/pen/YYYeRP

Idea is that clicking the first checkbox should toggle the other checkbox. Your guidance and help is appreciated!

**Comment by rikkit** [comment]
Hi, I'm learning RRF currently so thought I'd jump in and fix your codepen as practice if that's aight.

https://codepen.io/anon/pen/YYeGWr?editors=1111

Please excuse the lack of a proper write up, here are some notes on my implementation instead. There are a few comments in the codepen as well

- the "toggle all/ toggle none" is not bound to redux state - it's just a checkbox that dispatches an action. It could be a button instead (imo a button makes more sense from a UX perspective since the other checkboxes can be updated independently). It doesn't take a model name because AFAIK there's no built in react-redux-form action that toggles all the values in an array - because to maintain whether it should set all to true or all to false will depend on what the user of the library wants. Hence my usage of `actions.map` that simply changes all checkboxes to match the checked state of this checkbox. You could similarly implement "invert checkboxes" with `actions.map(x => !x)`
- for actions.map to work as expected, the local state needs to already have values. If you want to delay initialisation of the state, you could use `actions.change` in `toggle` instead - see comment
- checkbox B and C get bound to `local.cb[0]` and `local.cb[1]`, because their values should be the first and second values in the array. I think you can use `track()` function of RRF - i.e. set the model prop of both to `track(local.cb[])` - to make this automatic but I thought it'd be more helpful to start out this way.

Let me know if there's stuff I could explain better

**Comment by grks** [comment]
@rikkit Nice and thank you!
One thing, I sort of think it could be nice to keep the names in the store, as it could be more pleasant for debugging. But I guess that could be abstracted on top of this. I learned a lot from your example. Thanks again!

**Comment by grks** [comment]
@rikkit  I found one issue or maybe a bug with your approach.

Try this one: https://codepen.io/anon/pen/baMRRw

So idea is that it should update the values when you click checkboxA or checkboxB, but it only updates the model when you click the toggle all. Also then it only updates one of the values and not both.

That said, what is the difference between form.$form.value.cb and cb.$form.value  ? Which do you tend to use if you are going to do something with the form values?

**Comment by rikkit** [comment]
Hi @grks 

I notice you've hooked up the `onUpdate` prop of LocalForm to see the form model as it changes. I haven't checked exactly when this prop is called, but I think you mean to use the `onChange` prop instead. onChange is triggered whenever the model that's linked to the form component changes. It receives the new form model as an argument. https://codepen.io/anon/pen/wpjLdM?editors=1111  (I haven't changed the rest of the code)

> That said, what is the difference between form.$form.value.cb and cb.$form.value ? Which do you tend to use if you are going to do something with the form values?

I can't answer that, I know that $form objects are used to track the internal state of the form - each object in the structure of a form model has a corresponding $form object to track stuff like validation, whether the field has changed, etc. If you use the library with redux, you can inspect the redux tree to see what I mean - I am not sure how `LocalForm` implements this feature, but it looks to be different to `Form`.
