### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by Utkarsh-LiquidStone** [davidkpiano/react-redux-form#1222]
When I implemented the Control, LocalForm, Errors in my react application. I'm getting the following warning in console:

`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. `

`Please update the following components: Control, Form`

Can you tell me how to resolve this warning?  Please update.

**Comment by rikkit** [comment]
That warning is coming from React due to usage of componentWillReceiveProps in this library - React are planning to rename this method in v17. This library will need to be updated and re-released with a fix for this warning to work with React 17 - but until that is released, you can ignore this. More info here: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by Utkarsh-LiquidStone** [comment]
Thanks, @rikkit for the information.
