### ISSUE TITLE
Ability to use <Field> with React components?

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#123]
I noticed this is currently not possible:

```javascript
<Field model="model.name">
  <MySpecialInput />
</Field>
```

I'm wondering if there's a way to make this work, other than having to use an `onChange` handler on `MySpecialInput` and manually dispatch events to rrf?

**Comment by mdgbayly** [comment]
Hey Sam

Have you seen the createFieldClass examples in the [docs](https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html).

We use that approach to wrap a number of custom React components.

Cheers
Martin

**Comment by ffxsam** [comment]
@mdgbayly You rock!! Thank you for that awesome tip, I didn't even bother to look there.. I guess because the section says "React Native" so I skipped it.

**Comment by davidkpiano** [comment]
Good feedback @ffxsam! I'll make the title of that section more clear.

Also, much thanks @mdgbayly, hope that `createFieldClass` is working fine for you!

Off-topic: I was thinking of renaming this function `customField()` instead of `createFieldClass` in v1. Thoughts? Just wanted to make things more succinct/easy to remember, such as `createModelReducer -> modelReducer`, etc.

**Comment by ffxsam** [comment]
I think the name is good as is. It's descriptive, it's telling me that I'm creating a field class for my component. So for instance, in my code I now have this:

```
<TagInputField model="trackModel.tags">
  <TagInput ... />
</TagInputField>
```

IMO the name `customField` is less descriptive.
