### ISSUE TITLE
Question - Changing the validator doesn't seem to effect validity/requirement of field if already flagged as invalid

### ISSUE THREAD

**Issue by bgriffith** [davidkpiano/react-redux-form#182]
Hey David, still loving the library! :+1:

The app I'm working on has lots of forms that vary depending on what the user selects throughout. Therefore the fields shown and the object passed to the validator prop on the form can change at any time.

One thing I've noticed is that if I have a form where field A is required by the initial validator object, and field A gets marked as invalid (in the form reducer), if I then choose an option where field A is no longer required (and not in the validator object) the form will not submit as it considers it still required and sees that it's invalid.

Is this by design? And if so, what would be the best way to go about reseting which fields are required?

Is it with `actions.reset(formModel)` or manually resetting the validity of the field(s)?

Apologies if what I'm trying to achieve is not too clear.

**Comment by davidkpiano** [comment]
@bgriffith Thanks, I appreciate it!

Do you mean dynamic validation? As in:

```js

// given something like

render() {
  return <Field model="foo.bar" validators={ this.getValidators() }>
  // ...
}


// rendered state 1:
<Field model="foo.bar" validators={{ required }}>

// rendered state 2:
<Field model="foo.bar" validators={null}>
```

**Comment by bgriffith** [comment]
Hey @davidkpiano - Yeah I have something similar but on the `<Form>`.

Here's a quick gist I knocked up to help explain.

http://esnextb.in/?gist=10d57e542448b97ad80cf5bc22d64e70

In short, changing the validator object doesn't result in the form revalidating, and therefore checking to see if the previously invalid fields are still invalid.

**Comment by davidkpiano** [comment]
Quick solution:

Since your validator **depends on 2 or more fields**, it's best to move it a higher level; in this case, **form validation**. Take a look:

```js
  // Validators for the Form component
  let validators = {
    // form-level validation (empty string)
    '': {
      bRequired: (val) => val.a !== 'true' || isRequired(val.b)
    },
  };
```

Two other helpful tidbits:
- `checked={foo.a === "true"}` etc. is redundant; RRF does this for you 😉 
- If you want, you can pass in the actual `true` value; RRF is smart enough to know the exact value instead of blindly converting it to a string:

```js
<input type="checkbox" value={true} />
```

Let me know if this solution works for you! If not, I'll look further into dynamic validators, which is something I haven't considered yet, because of the ability to do validation at _any_ level in the form.

**Comment by bgriffith** [comment]
Ah awesome! A form level validator seems to do the trick and thanks for the tidbits :+1:

I'll let you know how I get on with this solution.
