### ISSUE TITLE
Warnings with react 15 about controlled/uncontrolled inputs

### ISSUE THREAD

**Issue by daneryl** [davidkpiano/react-redux-form#184]
When controlling an input by adding the value property react 15 throws a warning
```
Warning: Input elements must be either controlled or uncontrolled 
(specify either the value prop, or thedefaultValue prop, but not both).
Decide between using a controlled or uncontrolled input element and remove one of these props.
```

**Comment by davidkpiano** [comment]
Fix coming right up! (Was actually just working on this very issue)

**Comment by daneryl** [comment]
thank you !

**Comment by davidkpiano** [comment]
@daneryl Now, input elements are controlled by default (as long as `updateOn="change"`, which is the default anyway).

You'll still get the warning if you don't specify an initial value for each model, which is good practice:

```js
modelReducer('user', { email: '', name: '', ...etc })
```

**Comment by daneryl** [comment]
Working great with the default controlled inputs thanks. loving the library !

**Comment by greaber** [comment]
Why is it considered good practice to specify an initial value for each model?  I already write out all the values of the model in two places: the actual form component and the constructor.  Since the initial state is invalid, I can't construct it with the constructor.  Why is it good practice to list out all the fields in a third place, pairing them all with empty strings or other semantically null values?

**Comment by davidkpiano** [comment]
@greaber V1.0 will alleviate this requirement.
