### ISSUE TITLE
Question: Should Field components expose the form state to the controlled component?

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#210]
I'm frequently finding myself writing:
```js
            <Field model="model.field">
              <TextField
                label="A Field"
                invalid={isInvalid('field')}
                dirty={isDirty('field')} />
            </Field>
```

where `isDirty` and `isInvalid` are defined as:

```js
    const isInvalid = (field) =>
      (model_form.submitFailed && !model_form.fields[field].valid) ||
      (!model_form.fields[field].pristine && !model_form.fields[field].valid);

    const isDirty = (field) =>
      model_form.fields[field].dirty;
```

Aside from the sheer size of a field definition this also means:
1. The parent of the form has to be connected to the store to get `model_form`, I have in fact ended up with components connected to the store for *ONLY* this reason.
2. Parent components have to frequently duplicate or decide on the rules for when a form is invalid or dirty. Which leads to inconsistencies.

It seems like it would be nice if I could write something like…:

```js
<Field model="model.field" form="model_form">
 <TextField label="A field" />
</Field>
```

And do the appropriate mapping of the `model_form[field]` flags to the `textfield` props in createFieldClass. Which would give me the ability to specify them globally and consistently throughout my application.

**Comment by davidkpiano** [comment]
@dreid Actually, you already have this ability! It's just not documented (yet). You can do this in `createFieldClass(...)`:

```js
const MyField = createFieldClass({
  'TextField': (props) => ({
    invalid: !props.fieldValue.valid,
    dirty: !props.fieldValue.pristine,
  })
});
```

So, two important things:
- The field values, such as `valid`, `pristine`, etc. are all available on `props.fieldValue`
- Use the affirmative rather than negative prop names, e.g. `valid` instead of `invalid` and `pristine` instead of `dirty` because the negative prop names are redundant and will be removed in v1. I'd like to keep the size of the field objects down.

Hope that helps!
