### ISSUE TITLE
Can't create a component that acts as a checkbox.

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#223]
See http://esnextb.in/?gist=f0b9b22bbe837861533683dbfdd03ec4 for a minimal reproduction.

This appears to be because of the checkbox specific `modelValueUpdater` behavior which is not triggered except when `controlProps.type` is "checkbox".

As you can see from the esnextb.in simply specifying the type="checkbox" on the component is sufficient to workaround this issue.

I'm not sure what a good solution to this is, perhaps some mechanism to extend the `modelValueUpdaterMap` when doing `createFieldClass`

**Comment by davidkpiano** [comment]
This will be addressed more elegantly in v1.0; adding `type="checkbox"` is a sensible (and expected) workaround currently.

It has to do with how props are currently mapped for custom components - right now, there is no way of knowing the mapped props until _after_ `sequenceEvents`, and in V1 the mapping will be made available before sequencing.

**Comment by davidkpiano** [comment]
Available in latest `@beta`!

```js
<Control.checkbox component={...} />
```

**Comment by cal0610** [comment]
Thanks David, I scoured through all of the docs and couldn't find a way to hook up a custom toggle / checkbox with RRF. This should be included in the docs because there's some weird behavior.

`<Control component={CustomToggle} />
`
Clicking the checkbox would always provide a value "on".

The correct way is as you mentioned:

`<Control.**checkbox** component={...} />`
