### ISSUE TITLE
Why are validators in the view and not the store or reducer?

### ISSUE THREAD

**Issue by etrepum** [davidkpiano/react-redux-form#253]
It seems awkward that the validators reside only in the view, not in the model. This makes more complex validations that rely on the state of two or more components very manual and error-prone, and it makes it awfully tricky to fire off a request to validate a particular field (particularly if the view for that field is not currently being rendered, or if the validations have changed but the value of that field has not).

**Comment by davidkpiano** [comment]
Great question!

External validation via actions was a design decision from the very beginning, because **validation can occur at _any_ time**, not just when the model value changes. Consider the following common use-cases:

- Validation on blur
- Debounced validation
- Async validation
- etc.

> It seems awkward that the validators reside only in the view, not in the model.

Sort of, until you take asynchronous validators into account. Then it makes sense that the validators are _external_, and not in the reducer itself.

Don't think about validators as being view-only, but rather as being external - validation can occur anywhere that you can `dispatch()` a validation action. Which brings me to my next point...

> This makes more complex validations that rely on the state of two or more components very manual and error-prone

What would your ideal API for this look like? Currently, you can validate multiple fields by validating its parent:

```js
// in <Form>:
<Form model="user"
  validators={{
    '': {
      passwordsMatch: (value) => value.password === value.confirmPassword
    }
  }}
/>
```
```js
// Manual dispatch:
dispatch(actions.validate('user', {
  passwordsMatch: (value) => value.password === value.confirmPassword
});
```

> it makes it awfully tricky to fire off a request to validate a particular field

React Redux Form at its very core is just **actions** and **reducers**. Using `<Field>` and `<Form>` is _always_ optional, and there's nothing stopping you from using the provided actions and reducers to create functionality that fits your use case.

For instance, let's say you want to validate a specific field at any time, even if it's not rendered. A good pattern would be to store your validators in a shared file, such as `validators.js`, and then:

```js
import validators from '../path/to/validators.js';

// wherever dispatch() is available
dispatch(actions.validate('user.email', validators.email));
```

It's important to note that React Redux Form, just like Redux, provides the building blocks for you to be completely flexible in the way you build complex forms in Redux (and V1 will make it even more flexible). It's not a library that tries to do everything; it can do a lot, but there are hundreds of different use-cases for forms and being too opinionated about anything will alienate many of those use-cases.

It's important that React Redux Form errs on the side of being unopinionated, even if it involves a little more code. If the API allowed the user to define validators directly on the reducer, the following issues may occur:

- Different mechanisms for sync and async validators instead of treating them equally
- Inability to conditionally define validation via props
- Very difficult to validate on blur
- Impossible to validate on debounce
- Impossible to validate asynchronously
- Lack of flexibility in validating at any time

So, what would your ideal API that allows the above flexibility look like? I'm always open to suggestions.

**Comment by etrepum** [comment]
Validation can indeed occur anywhere that actions can be dispatched, but if you define your validators in a Field then there is no straightforward way to trigger that validation action without also storing the validations that are applicable to that Field somewhere outside of the view.

Conditionally defining validation via props doesn't really work as I would expect it to, because if the props change without the model value changing then a revalidation does not occur. There's no straightforward way to convince a Field that it needs to revalidate without also changing the model value.

I suppose the real problem is that having validators on a Field is opinionated and not quite as flexible as it appears to be, and that a coherent and convenient way to deal with them (without propagating onChange/etc. all over the place) outside of Field/Form isn't demonstrated in the docs. Having them on the Form also appears to be a bit inflexible such that validators must all be validated on change, or they must all be validated on submit.

I haven't put too much thought into what an ideal API would look like. As you've said, there are a lot of things to consider around asynchronous validators (debouncing can be considered a specific case of async). All of the synchronous concerns are possible to sort out in a reducer as it's straightforward to have one that has access to both the current and next form and model state. If the validators were in the store as well, then manipulating the working set of validations would also be straightforward.

**Comment by davidkpiano** [comment]
You bring up some very good points, about having a centralized way to do validation (I agree, having them on `<Field>` and `<Form>` is a bit inflexible).

With that said, we need to rule out validators being in the reducer - they don't belong there unless we want to completely discount async and non-change-based validators. So we have two options for a cleaner, centralized validation API:

- Validators as middleware
- Validators in the action creators

Middleware might be the best option - that would allow us to intercept actions and, based on a per-validation config, specify when the validation should occur, and for what fields. And it can be asynchronous!

Then a V1 validation triggered for a field would be as simple as:

```js
dispatch(actions.validate('user.email'));
```

Thoughts on custom middleware?

**Comment by etrepum** [comment]
Yeah you're absolutely right, should not be in the reducer unless it's idempotent, and in these cases it's not always going to be (especially in the async case).

Middleware sounds like a great option! I can't think of any caveats to that… other than, of course, the work to implement it and transition to using that instead :)

**Comment by etrepum** [comment]
Not sure what your protocol is for closing these kinds of question issues, but you've definitely satisfied this query from my perspective so I'll go ahead and close it (feel free to re-open of course). Thank you!

**Comment by davidkpiano** [comment]
We can continue to discuss here or elsewhere, would love to know your use cases for non-trivial validation!

**Comment by etrepum** [comment]
The use case we have is that some enumeration (radio/select/checkbox) determines how other parts of the form should be displayed and/or validated.

For example, a shipping form where there is a country selector and the validators are on the Field components:
* If the country is US, display the subset of the form that has a US address and relevant validations (city, state, zip)
* Otherwise display a subset of the form that has a more free-form address input with much more relaxed validation rules

A case where this breaks down is:

* Select US
* Enter an invalid zip code into the form such that it does not pass the validator
* Select a non-US country (which no longer has a Field with a validator for zip code)
* Complete the non-US subset of the form passing all of the current validators
* The form can not be submitted because it is invalid (since the zip code will be considered invalid until revalidated but it will never be)

This can be worked around if the validators are on the Form but not if they are on the Field.

**Comment by davidkpiano** [comment]
Yeah, this is the perfect use-case for (async because validating zip) validation on `<Form>`. Keep in mind that if form-wide validators were allowed on `<Field>`, then `<Field>` would need to rerender any time _any_ part of the form changes, which is a significant performance hit.

**Comment by etrepum** [comment]
I think that perhaps zip was a bad example, I'm not talking about an async validation here, just a field that should only be validated at all given some particular value of another example. Pretend I said state instead :) Our actual use case is not exactly this, I was translating it to something a bit more common.

**Comment by etrepum** [comment]
Note also that the downside you mention is only true if validators are specified with exactly the same API that exists today, if the field dependencies can be specified statically there is absolutely not a requirement that anything happens any time any part of the form changes. It's also certainly not true that evaluating a validation means that the field needs to be re-rendered.
