### ISSUE TITLE
defaultChecked for inputs of type radio and checkbox doesn't work

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#265]
The `defaultChecked` prop on inputs of type radio and checkbox does not work while `checked` works and `defaultValue` on inputs of type text work too...

Version: 0.13.6

**Comment by zabojad** [comment]
Also, when using `defaultChecked` on radios and checkboxes with RRF, I have the following warning:
```
Warning: A component is changing an uncontrolled input of type radio to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```

While I do not have this warning with pure React js (no RRF involved)...

**Comment by davidkpiano** [comment]
Right, because `defaultChecked` is for _uncontrolled_ components, and RRF makes radio and checkbox components controlled so that they can be updated externally. 

Are you sure that you want your radio and checkbox components to be _uncontrolled_ components? If you are using Redux, you can accomplish the same behavior by setting an initial state for the models that these radio and checkbox components represent. This is the recommended approach.

However, I will create a patch that lets radio and checkbox components remain uncontrolled if you specify `defaultChecked`. Just keep in mind that this will remove the ability for RRF to externally check/uncheck these components from outside changes.

**Comment by zabojad** [comment]
@davidkpiano I'm actually using this because in the case of this form, I do not know the initial state at application startup. The initial state is dynamic and fetch from the server.

How should I set the initial form state in that case ?

**Comment by zabojad** [comment]
PS: does it mean I should not use `defaultValue` on inputs type text too ?

> Just keep in mind that this will remove the ability for RRF to externally check/uncheck these components from outside changes
What does it means more practically. What will and what will not work ?

**Comment by davidkpiano** [comment]
Ah, gotcha. You can dispatch `actions.change(model, value)` at any time once you receive the data from the server. Would that work for your use case?

```js
getDataFromServer()
  .then(result => {
    dispatch(actions.change('user.name', result.name));
  })
```

**Comment by davidkpiano** [comment]
And yes, you should try to avoid `defaultValue`.

**Comment by zabojad** [comment]
ok, I'll do that instead... Thank you !

**Comment by zabojad** [comment]
PS: can we dispatch the entire model value at once, ie:
```
dispatch(actions.change('user', { name: result.name }));
```

**Comment by davidkpiano** [comment]
Yeah, absolutely!

If you want to merge parts of the model with the entire model, you can also do this:

```js
dispatch(actions.merge('user', { name: result.name }))
```

which is useful if your `user` model has more fields than just `name`.
