### ISSUE TITLE
Dynamic default value for input type text

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#268]
As per #265, I know use `props.dispatch(actions.change("model",value))` to set an initial form state dynamically.

However, this doesn't seem to work on input type text: http://esnextb.in/?gist=68458c20fce449d3657970658e922a32

**Comment by zabojad** [comment]
It seems to be because of the updateOn="blur". How can I bypass this for the initialization of the default state?

**Comment by davidkpiano** [comment]
If an input has `updateOn="blur"`, then it is an _uncontrolled_ component by necessity right now (because a connected input represents the state, and if you are still focused in the input and type a value, the input's value is not the same as the input's state until you blur).

This will be solved in v1.0. For now, you might need to remove `updateOn="blur"` if you want it to update, or have the component be controlled yourself.

You also don't have to use `<Field>`. You can always dispatch the actions directly from your component, such as:

```js
<input value={this.state.foo}
  onBlur={(e) => dispatch(actions.change('user.foo', e))}
/>
```

**Comment by zabojad** [comment]
There is some incoherence here... updateOn="Blur" should make the component "half controlled", not uncontrolled at all... I don't see what is the use on this `updateOn` prop on `Field` if it make the `Field` component itself useless...

If it were *half controlled* (synchronizing with the form model/state only at initialization and on blur), then I could have workaround my issue simply by rendering the form after setting the form initial state...

**Comment by davidkpiano** [comment]
There is no such thing as a "half controlled" component. It is either fully controlled or fully uncontrolled; React will throw a warning if you go from making a component uncontrolled to controlled (and vice versa).

This will be fixed in V1 by making the component **fully controlled** with regard to its `viewValue`, which may differ from the `modelValue` in that it is always in sync with the `modelValue` but not the other way around.

If you are not loading data in asynchronously and using the input as a normal text field where values always come from the user, `updateOn="blur"` does not make the component "useless" because it will work as expected.

**Comment by davidkpiano** [comment]
This is fixed in the latest `@beta`, now that the component is *fully controlled* regardless of blur/change.

**Comment by skeletorkun** [comment]
I have spent the entire day looking for a proper example of ' dynamically updating the initial values' it would be worth adding this in examples. @davidkpiano
