### ISSUE TITLE
Production ready / semver

### ISSUE THREAD

**Issue by chrisblossom** [davidkpiano/react-redux-form#27]
@davidkpiano Thank you for all of your work on this. In your opinion, is this production ready? Also, would you consider transitioning to semver?

**Comment by davidkpiano** [comment]
Thanks, @chrisblossom! I have been using it in a production app with complex, multi-page forms for the last month and it has been working well. I'd consider it stable enough to use in production since it is using vanilla Redux for the most part, which itself has a stable API.

The library itself is already using semver, and had had no breaking API changes so far, only bug fixes and feature additions. Once enough people are using it and the features and API are satisfactory for any non-trivial use case, I'll bump it to 1.0.0. 

Hope that helps!

**Comment by chrisblossom** [comment]
Thanks for the quick response! 

According to http://semver.org:
```
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```

So since you are already following semver I should not consider this stable and not production ready, correct?

**Comment by davidkpiano** [comment]
I would say to use it at your own discretion, much like how React was at version `0.x` for a while until they finally decided it was _already_ being used widely in production.

But know that I don't anticipate the API to change, since this is based on years of working on very complex forms in Angular, React, and plain JS, as well as researching all the available APIs and libraries for handling form state in Angular and React (such as `redux-form`).

The only way there would be major breaking changes is if Redux itself introduces breaking API changes, which is highly, highly unlikely.

**Comment by chrisblossom** [comment]
I appreciate the React reference, but they are not going to follow true semver until 15.0.0. Also react is completely different as it was used in production on Facebook prior to being released to the public as well as the power of Facebook behind it.

Sorry, I am not trying to argue, but trying to make a decision to use this or redux-form. I just figure if you are saying you are happy with the API as it is and you feel it is relatively stable, I think that should warrant a 1.0.0 release following semver. Could always post a warning about your concerns about it not being 100% production ready.

**Comment by davidkpiano** [comment]
I completely understand. I do feel that it's stable, but I'd like others to use it extensively before I move it to 1.0.0. I actually wrote this library in response to `redux-form` in order to provide stability - a lot of the issues (100+) on `redux-form` are a result of the library trying to handle too much and mix form state with model state, which exponentially adds complexity.

This library separates the two, which dramatically decreases complexity (and library size) - the library is simply a collection of actions and reducers, with a few helpful (but optional) additions such as: 

- `<Field>` component wrappers
- `modeled()` reducer enhancer

and a few action thunk creators that make composing complex actions, like asynchronous validation, easier. It works by using vanilla Redux (and allowing you to use plain Redux) as much as possible, without trying to assume too much control over your form state.

Redux-Form is `v.4.x.x` right now, indicating that it _already_ has had many breaking API changes. It also takes control of your form state, in that you have to do most form-related things through the API it provides _rather than_ through Redux yourself (which Redux-Form discourages). This makes it hard to do non-trivial or complicated form actions/updates, but if your form fits in the use-cases outlined in the Redux-Form documentation, and doesn't try to do anything too crazy, Redux-Form should be fine for you.

If you are comfortable with Redux and want to know exactly how everything is happening without introducing too much "magic", then that's why I built React-Redux-Form :smile: It's best suited for those who _already_ have an application that they want some form control over, or those who want to write minimal code and are comfortable creating their own actions and reducers as well.
