### ISSUE TITLE
Async-validation removes sync-validation state?

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#277]
Hi,
(react-redux-form 0.13.7)
I've implemented a login form for the username with some sync-validations and a async-validation which checks if the username is already in use like in your example of the docs: 

```jsx
<Field model="user.username"
  validators={{
    minLength: (val) => val && val.length > 6 // I changed this to show the issue
  }}
  asyncValidators={{
    available: (val, done) => asyncCheckUsername(val)
      .then(res => done(res.available))
  }}
  asyncValidateOn="blur">
  <input type="text" />
</Field>
```
Doing so, my sync-validation result will be cleared when the async-validation result will be added to the store. This causes a leak as when I write a username with just 4 letters it is invalid till the check to the server says simply: oh, this username isn't used yet. 

As the sync-validation-result gets overwritten by the async one the field will be labeled as valid – but it shouldn't as the username-value has just 4 letters.

Is there a way around?

**Comment by MiMaMuh** [comment]
Hi, thx for your quick fix!

It seems there ist still an issue: It works when a sync-validation is followed by an async-validation. But when a sync-validation follows an async-validation the store will be overwritten as before.

**Comment by MiMaMuh** [comment]
Hm, just considering it: It isn't really an issue. I think it is needed by concept this way otherwise there are conflicts when the value gets changed and the async-error prompts the field is invalid till it gets new results even it may be corret – tricky.

**Comment by davidkpiano** [comment]
@MiMaMuh: 

> Hm, just considering it: It isn't really an issue.

This is what I consider as well. Here's my thoughts, assume you have two validators:

- (sync) `required`
- (async) `available`

Now consider the following changes:

1. `''` results in `{ required: false }`
2. `'taken'` results in `{ required: true }` and triggers async validation...
3. `'taken'` is not available, so `{ required: true, available: false }`
4. `'not-taken'` executes `setValidity` which overwrites the validity to `{ required: true }`

The fact that the `{ available: false }` validity is overwritten (removed) in 4 makes sense, since `{ available: false }` is a validity that only applies to the value `'taken'`, and not the value `'not-taken'`.
