### ISSUE TITLE
Field with updateOn="blur"  does not reflect model value

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#278]
Example: http://esnextb.in/?gist=1225a9edcb310e0dd7a64e88a9f80562
Took a look at 2 emails fields. One will get loaded value, and one will stay empty.

Also this bug occurs with ``parser`` property. Field does not retrieve new parsed value.

**Comment by davidkpiano** [comment]
This is because `updateOn="blur"` fields right now are *unconnected* fields - since they reflect the model value, they can't be connected to the `modelValue` if they're only updated on blur.

I'm working on resolving this in V1. The idiomatic way to handle this right now is to control the `<input>` yourself, using `this.setState` in the `onChange` handler.

**Comment by gregnorris** [comment]
Is there an easy way to do that right in the call to <ReactReduxFormField model={ model } updateOn="blur" .... ?
If you could throw a snippet of code, that would be fantastic.

Thanks!

**Comment by davidkpiano** [comment]
This is fixed in the latest `@beta`.
