### ISSUE TITLE
Problem with form Model validation

### ISSUE THREAD

**Issue by matias89** [davidkpiano/react-redux-form#298]
Hello! I'm executing "setValidity" function when I click in the onSubmit button (`<Form model="userProfileForm" onSubmit={this.handleSubmit}>`), but the first time userForm.valid returns true when should return false.

Example:
```
handleSubmit() {
     this.props.formActions.setValidity('userProfile.name', { required: false });
    console.log(userProfileForm); // This returns true the first time when the form is submited, and the others time this returns false.
}
```

My input is:
```
<Form model="userProfileForm" onSubmit={this.handleSubmit}>
<Field model="userProfile.name">
    <input type="text" />
</Field>
<button type="submit">TEST</button>
</Form>
```
![ezgif-1900187333](https://cloud.githubusercontent.com/assets/5619274/16532405/21d87a0c-3fa8-11e6-84ad-54c4b79b7047.gif)

**Comment by davidkpiano** [comment]
Right, because at the point you dispatch that action, the component has _not_ rerendered with the new props yet until it finishes execution of that method. You can't treat dispatching an action as imperative, you have to wait until the component rerenders with new props.

This is what's happening:

- `setValidity` action dispatched
- `userProfileForm` is still valid because changes haven't propagated yet
- **at this point** method is completed and component rerenders with new state
- _now_ `userProfileForm` is invalid.

**Comment by matias89** [comment]
Thanks for response. Then: how I can get the form validation when I submit my form?

**Comment by davidkpiano** [comment]
You can get it from `userProfileForm.valid` and `userProfileForm.validity` (which is more detailed).

Also, you can get the validity of each field: `userProfileForm.fields.foo.validity`

**Comment by matias89** [comment]
Sorry, but I can't understand, because if I don't add or change any text in the form when I load it the first time, and the form is submited, and in my submit function I use "setValidity" for required field (false), I can't get the validation with "userProfileForm.valid".

**Comment by davidkpiano** [comment]
Can you please post a code example on www.esnextb.in ?

**Comment by matias89** [comment]
Yes: https://esnextb.in/?gist=0bd9c168f58a07e29cae94483cf699b1

**Comment by davidkpiano** [comment]
Two things:

First, make this change:

```diff
- userProfileForm: formReducer('userProfileForm')
+ userProfileForm: formReducer('userProfile')
```

to let RRF know that this `userProfileForm` is for the `userProfile` model. (This will be greatly simplified in V1).

Secondly, since dispatching is not synchronous, you will have to check the validity in `componentWillUpdate` or a similar method. If you don't enter a value and click `submit` twice with the modification above, you will get `true` (because the dispatch happened asynchronously) and then `false` the second time you clicked it.

**Comment by matias89** [comment]
I'm sorry, I was with many other things during these days. I understand what did you say, but then: how I can set by default the property in "false" (in my case, userProfile.valid false by default)?

**Comment by davidkpiano** [comment]
Add a validator:

```js
        <Field model="userProfile.test" validators={...}>
          <label>Test </label>
          <input type="text" defaultValue="" />
        </Field>
```

If it's `.valid === false` by default, and there are no validators, it will never be valid. Validators are run immediately when `Field` is mounted.

In V1.0 there will be the option to let you specify the default initial state, and customize form behavior via plugins.

**Comment by matias89** [comment]
Ok, I'll test this. Thanks David!
