### ISSUE TITLE
Thoughts on making a Field like higher order function instead of parent component?

### ISSUE THREAD

**Issue by webmasterkai** [davidkpiano/react-redux-form#3]
I was really excited to discover your new module last night. I like the approach but found myself a bit confused over the Field component. It's obviously optional but I find myself longing for a higher order component I could pass a component to as an argument and have the event handlers and state slice applied as props to it. That way I can be sure to link to them up to the correct places within the custom component I send to it. Any reasons you decided against it in favor of the current `<Field>` approach? Thanks for your all your work thus far.

**Comment by davidkpiano** [comment]
Hey, great question, @webmasterkai! A few months ago, I played around with approaches such as:

- `<input type="text" {...field('foo.bar')} />`
- `{ field('foo.bar', <input type="text" />) }`
- `export default field('foo.bar')(<MyInputComponent />)`

but ultimately came to the `<Field>` approach for a few reasons:

- Reconciliation - because `<Field>` is a React component, I can manually adjust reconciliation so that the component only re-renders when it needs to
- Recognition of control components - gives `<Field>` the ability to treat input, radio boxes, checkboxes, select, etc. differently (an important distinction from Redux Form)
- Multiple child components - since `<Field>` recursively goes through its children to figure out what's a control component, it will smartly handle:

```js
<Field model="foo.bar">
  <input type="radio" value="Option 1" />
  <input type="radio" value="Option 2" />
  <input type="radio" value="Option 3" />
</Field>
```

without any extra effort on the developer's part.

I'm going to be writing some documentation on how exactly `<Field>` works, but the basic gist is this:

- It figures out what type of control component(s) it is dealing with, so it knows exactly how to update/apply the model value to it
- It `compose()`s a series of actions to each control's event handlers, so that it properly handles validation and updates exactly when you specify (`onChange`, `onBlur`, debounced, etc.)
- It returns all children (wrapped in a `<div>` if there's more than one) that only rerender when absolutely necessary

And probably the biggest reason for it being a self-contained component: it can live within an unconnected parent component:

```js
// No need to connect() this!
export default class MyForm extends React.Component {
  render() {
    return (
      // <Field> connects itself!
      <Field model="user.foo">
        <input type="text" />
      </Field>
    )
  }
}
```

Hopefully that answered your question! I'm open to hearing alternative approaches that also provide the previously mentioned solutions!

**Comment by webmasterkai** [comment]
Thanks for the response. That's helpful.

Does the following pseudo-code work for you? I've tried a few variations but can't seem to get it to work like it does when each option is a direct child in same component as in your radio example above.

```javascript
export default function Options() {
  const options = [ { value: 'opt1' }, { value: 'opt2' }, { value: 'opt2' } ]
  return (
    <div>
      { options.map(opt => <input type="radio" value={opt.value} />) }
    </div>
  )
}
```

```javascript
import { Field } from 'react-redux-form'
import Options from './Options'

export default function MyRadioField() {
  return <Field model="user.foo"><Options /></Field>
}
```

I stumbled upon a similar issue on another React module that does some "magic" props application to children via parent component https://github.com/soundblogs/react-soundplayer/issues/9
`¯\_(ツ)_/¯` if it works, it works? I'll just have to take a deeper look into `src/components/field-component.js` and see why I'm having trouble.

**Comment by davidkpiano** [comment]
Okay, what RRF is doing is checking that any of its children either:

- are a control (such as `<input>`, etc.)
- have children, that are a control (recursive)

When `<Field>` encounters `<Options>`, it sees that it is neither a component nor does it have any children, interestingly enough (because it wasn't "rendered" yet... I'll have to look deeper into functional components for this nuance).

This **will work**, however:

```js
function Options() {
  const options = [ { value: 'opt1' }, { value: 'opt2' }, { value: 'opt3' } ]
  return (
    <div>
      { options.map((opt, i) => <input type="radio" value={opt.value} key={i}/>) }
    </div>
  )
}

function MyRadioField() {
  return <Field model="user.foo">{Options()}</Field>
}
```

**Comment by leandroz** [comment]
I think I am having the same problem with AutoComplete from Material-UI.
I checked the examples for Slider and Checkbox and also implement the same for SelectField, but I can't make it work for AutoComplete (Is related on how the AutoComplete is generated).

What do you think would be a posible solution?

**Comment by davidkpiano** [comment]
@leandroz Here's how you would do it without `<Field>`:

```js
import { actions } from 'react-redux-form';

// in connected render():
const colors = [
  'Red',
  'Orange',
  'Yellow',
  'Green',
  'Blue',
  'Purple',
  'Black',
  'White',
];

<AutoComplete
          dataSource={colors}
          onUpdateInput={e => dispatch(actions.change('user.color', e))}
          onNewRequest={e => dispatch(actions.change('user.color', e))}
        />
```

**Comment by leandroz** [comment]
Thanks for the response @davidkpiano !
