### ISSUE TITLE
Trigger validation from an action

### ISSUE THREAD

**Issue by sattaman** [davidkpiano/react-redux-form#31]
I have noticed that validation does not fire for fields updated via actions.change

Also, is it possible to trigger the validation from an action, without repeating all the validation logic in the action? 

Hopefully I'm not missing something obvious, I've been trying to work out how I could do it.

!) Repeat validation logic in page and in action

2) Move all validation into an action and then trigger the action for all fields blur events.

Thanks

**Comment by sattaman** [comment]
Ive also noticed that there is a validate action in fields actions so may be able to figure it out ... 

```
const validate = (model) => ({
  type: actionTypes.VALIDATE,
  model
}); 
```

**Comment by davidkpiano** [comment]
Can you provide a code example for this: 

> I have noticed that validation does not fire for fields updated via actions.change

I was not able to replicate it.

Also, there is the `setValidity` action creator (as well as `setErrors`), are you trying to validate on blur? Or possibly on form submit?

**Comment by sattaman** [comment]
So I have an Field set to validate on change

```
    <Field model="myModel.field"
                            validators={{ required: (val) => { return val && val.length} }} validateOn="change">
                <input type="text" value={myModel.field} />
            </Field>

```

This works but if I change the model through an action 

`actions.change("myModel.field", "newValue") `

The validation is not triggered

**Comment by sattaman** [comment]
Regarding my validation, I need it to be both onChange and triggered by an action. If the validation reran on change I suppose I could trigger change on all my fields with the same data?

**Comment by davidkpiano** [comment]
Unfortunately, in `<Field>`, this has to do with how React works in that it won't trigger `onChange` events when input values are changed programmatically: https://github.com/facebook/react/issues/1152

Is it feasible to manually do validation, wherever you are dispatching the `change` action?

```js

function doChange(val) {
  return (dispatch) => {
    dispatch(actions.change('foo.bar', val));
    dispatch(actions.setValidity('foo.bar', {
      required: val && val.length
    });
  }
}
```

**Comment by sattaman** [comment]
I am not changing the value outside of react though, I am using the action to change them? 

I can do, although it would be better to have validaiton logic one place . One thing I did like about redux-form was how it handled validation, having a pure function doing it meant it could be tested in isolation. I also like being able to set the error messages to be displayed. 

I have been wondering about how it could be done, an action which took this pure function and applied it to existing validaiton, and Fields wrapped so they automatically called it on change? I noticed that one of your recent changes was to allow string error messages returned from promises.

**Comment by davidkpiano** [comment]
I'm experimenting with what the API could look like for this, while using 99% of the existing RRF constructs such as `setValidity` and `setErrors`:

```js
import { Form } from 'react-redux-form';

// somewhere connected in render()...
<Form validators={{
    // Form validation
    '': {
      passwordsMatch: (user) => user.password == user.confirmPassword,
      required: (user) => user.username.length && user.password.length
    },
  
    // Field validation
    'password': (user) => isValidPassword(user.password),
  
    // Async validation
    'username': (user) => (done) => asyncIsAvailable(user.name).then((res) => done(res))
  }}
  validateOn="submit">
  <Field model="...">
</Form>
```

And of course, that validation object can live in its own constant, such as `const validators = { ... }`. Would this approach make sense?

The reason that I don't agree with it being in a single function is that the function isn't smart - it has no way of knowing which parts of the validation to run on each change (unless you explicitly tell it when it should validate), meaning that redundant validation is being run on _every single change_ - this hinders performance and is entirely unnecessary. With the above approach, it can easily be optimized to:

- only run validation when the respective fields have changed
- handle both synchronous and asynchronous validation declaratively
- specify when validation should run (e.g. on `submit`).

Thoughts?

**Comment by sattaman** [comment]
Yes I like the idea of separating the validation, and I get your point about performance. Some features I'd be really interested are:

- validation to be triggered by actions.change
- form wide validation to be triggered from an action
- ability to specify error text from validation

Being able to set error messages from the validation would be really useful from me. I haven't got my head around what you have already implemented, but I think I saw presently you can set the text if using promises? I dont know whether you could use true or text could be an error and empty or false for no error? 

I've been playing with wrapping the field and bootstrap input into a component, which would handle the logic for applying the error highlighting, and uses the help property to display any error message. I suppose if the validators could be defined at the form level then they could be removed from this.

```
const ValidatedInput = ({model, validators, field, ...rest}) => (
        <InputFormField model={model} validators={validators}>
            <Input help={field.errors} bsStyle={field.valid ? null : "error"} {...rest}  />
        </InputFormField>
    )
```

**Comment by davidkpiano** [comment]
> validation to be triggered by `actions.change`

This is an interesting topic, because it can be **active** where an action would fire off another action, or **passive** where _something_ is listening for the `change` action (not the reducer - doesn't belong there). The active case is a no-go because we don't want to overload the `change` action with validation logic (or do we... hmm), and the passive case is best solved with custom middleware that can intercept the action.

However, a third solution can be...

> form wide validation to be triggered from an action

which composes well with the above `<Form validators={{...}}>` proof of concept, in that it doesn't have to listen for specific actions per se; it just has to know which fields have changed (which can be quickly done, depending on the depth of the model and the number of validators).

So, raw value comparison = simplest answer :+1: 

> ability to specify error text from validation

Sure, I'm going to document this, but you currently can do this:

```js
import { actions } from 'react-redux-form';

// somewhere dispatchable
dispatch(actions.setErrors('user.email', 'This email address is already registered.'));

// or as an object...
dispatch(actions.setErrors('user.email', {
  required: 'You need to enter an email address.'
}));

// or even as an array...
dispatch(actions.setErrors('user.email', [
  'Email not long enough', 'Email contains invalid characters'
]));

// or as anything else, really.
```

where any non-falsey value will indicate to RRF that there's an error.

Currently, with `<Field validators={{...}}>`, it's just a map of values that expects a boolean return value so that:

- validation can be easily composed and checked
- custom error messages can be placed directly into the UI, instead of returned from something like `setErrors`

The second point is important for `<Field>` since it assumes that if you're defining your validators directly in the `render()`, you're also able to define the error messages directly in the `render()`. This is so that you can quickly add common functions such as `{ valid: validators.isEmail }` instead of `{ valid: (val) => validators.isEmail(val) ? null : 'Email is not valid' }`.

**Comment by davidkpiano** [comment]
@sattaman The `<Form>` component described above (without the async validators) has been implemented in `0.7.0`: https://github.com/davidkpiano/react-redux-form/releases/tag/v0.7.0

Please let me know if this fits your use case!

**Comment by sattaman** [comment]
Ok cheers, that was quick! A few quick questions

- Does form validation run for fields changed via actions?
- Is it possible to trigger the validation from an action? 
- In order to specify error text, do I need to validate inside of an aciton?

**Comment by davidkpiano** [comment]
> Does form validation run for fields changed via actions?

**Yes**, it can! Just add `validateOn="change"` to the `<Form>` component, and it will run validation on the validators defined in `<Form validators={{...}}>` whenever the field values change, regardless of if it's from the field change or from an action.

If you want to have validators defined inside `<Field validators={{...}}>` to be run on value change (rather than on physical input change), please open up a separate ticket for that feature request. I think it might be a good feature to have.

> Is it possible to trigger the validation from an action?

**Yes**, now it is, with `0.7.1` (just released). Here's the idea:

- Your validators are defined inside a shared object, perhaps in a file like `validators.js`
- You can reference validators from anywhere
- You call `actions.validate(model, validators)` from anywhere with `dispatch()`.

```js
import { actions } from 'react-redux-form';

// your custom shared validators
import validators from '../validators';

// somewhere with dispatch()
dispatch(actions.validate('user', validators.user));
```

> In order to specify error text, do I need to validate inside of an action?

**Yes, but it makes sense to do so.** Validators defined inside `<Field>` and `<Form>` only care about the validity (`true/false`), and it's up to you to map that validity to the error messages, which are primarily a _view_ concern.

However, you can use `actions.submit(model, promise)` to automatically set the `.errors` property of the field state to whatever error the promise throws.

**Comment by sattaman** [comment]
Brilliant, will update. Thank you!
