### ISSUE TITLE
Is it possible to have nested collections?

### ISSUE THREAD

**Issue by hgylfason** [davidkpiano/react-redux-form#313]
Is it possible to have nested collections?

E.g. if this would be my data model:
`{
  groups: [
    { 
      id: 11,
      values: [
        {id: 1, value: 10},
        {id: 2, value: 13}
      ]
    }
  ]
}`

Is there some way to point to the "value" property?

This is what I've tried for fields (id is available from the outer context) with no success.
`
<Field model={track(model('groups[].values[].value'), (value) => value.id === id)}>
`

**Comment by davidkpiano** [comment]
So the issue here is that `track(...)` answers the question "Which item in the collection should we refer to?" However, you're trying to identify two things at the same time: an unknown collection that contains items which themselves might contain the item you're talking about (nested collections).

So, it would be best to identify the outer collection model first (and you can use any method you prefer), and then use `track` as normal:

```js
// determined somehow
const collectionModel = 'groups[3]';

// ...
<Field model={track(`${collectionModel}.values[].value', { id })} >
```

**Comment by hgylfason** [comment]
Ok, that is probably it. Thank a lot for the quick reply and for this brilliant library.

Would you consider making `track` handle multiple layers of collections in the future*?
E.g. `track` could receive a list of predicates and would use them to identify item in each collection.

*I admit I am not familiar with the inner workings of `track` so please dismiss this if it's not applicable.

**Comment by davidkpiano** [comment]
@hgylfason All `track` is is a function that returns a "model getter". That might still sound complicated so read here to see how it's created: https://davidkpiano.gitbooks.io/react-redux-form/content/tracking_collections.html
