### ISSUE TITLE
Form values are modelled by both modelReducers and formReducers

### ISSUE THREAD

**Issue by richardscarrott** [davidkpiano/react-redux-form#328]
The [form reducers docs](https://github.com/davidkpiano/rrf-docs/blob/master/form_reducers.md ) stress that the form values aren't modelled under the form state however I don't believe this is true as of https://github.com/davidkpiano/react-redux-form/commit/ecade1d6dcaf642fd559c603d79d3618905fe67d#diff-fcd205c3f8e04d4b3862b897f978e030R154

I guess the reason I came across this is because I'm trying to work out the real differences / purposes of `modelReducers` vs `formReducers`?

**Comment by davidkpiano** [comment]
One of the main design goals of RRF is with flexibility, in that:

- You can use your own reducers
- Model reducers can exist without form-related meta information

The `value` property was added just to keep track of value equality, whether the value changed from its initial value, and optimize performance - it should be considered an internal property and not used as if it were the actual model value (even though it is).

Does that answer your question? I can go more in depth if you'd like.

**Comment by greaber** [comment]
This is related to a question I have.  Before I was using React Redux Form, I had my own actions that would update parts of my model.  But now if I want to update parts of my model, I have to use the React Redux Form `change` action because otherwise the form reducer won't know anything has changed, right?  So, this means I have to rewrite any reducers that were responding to those old update actions and teach them to parse RRF `change` actions (except in the special case that they weren't doing anything except updating the model, so that using `modeled` is enough).  Or is it a good strategy to just fire my update action and _then_ fire the `change` action (possibly causing some double updates, which would be harmless)?

**Comment by richardscarrott** [comment]
@greaber Not 100% sure I'm following as I'm not massively familiar with RRF but if you needed to fire multiple actions to update RRF state and your own custom model state then I think you'd incur multiple store change events which would be more expensive. You could look at https://github.com/tshelburne/redux-batched-actions to mitigate this however.

**Comment by davidkpiano** [comment]
@richardscarrott RRF already uses a batching strategy :) For example, if you had `updateOn="blur"`, then you would dispatch a single batch action:

```
[
  { type: actionTypes.BLUR, model: '...' },
  { type: actionTypes.CHANGE, model: '...', value: '...' },
]
```

**Comment by davidkpiano** [comment]
And @greaber V1 will allow you to specify plugins for the `formReducer`, which allows you to create a plugin that tells the `formReducer` to listen for your own actions as if they were RRF `change` actions. More on this soon - I'm preparing an alpha release for V1!

**Comment by greaber** [comment]
OK, cool, looking forward to 1.0.  Although I wonder if it won't be better to just teach reducers to respond to `change` actions since they will be generated in response to user interaction even if there are custom actions that change the model in different cases (at least if using the `Field` component, unless that is also changing).

**Comment by davidkpiano** [comment]
V1 is out! I will have docs for form plugins soon.
