### ISSUE TITLE
Issues with react-bootstrap

### ISSUE THREAD

**Issue by sattaman** [davidkpiano/react-redux-form#36]
I've created an example: 
http://esnextb.in/?gist=61d8891f6bb8e6a5009b

I'm still having issues I was wondering if you could have a look. If you view the console, the action seems to always fire with true.

**Comment by sattaman** [comment]
I'll close for now as the above seems to be a bug in exnextb.in , they're still not working in my project but seem to be in a text project ive set up so will investigate further..

**Comment by davidkpiano** [comment]
Hey @sattaman, try doing this:

```diff
const store = compose(applyMiddleware(thunk, createLogger()))(createStore)(combineReducers({
-  fields: createModelReducer('myModel')
+  myModel: createModelReducer('myModel')
}));
```

The model name needs to match the actual key for the slice of state that the model represents.

Proof that that might fix your problem:

<img width="233" alt="screen shot 2016-02-29 at 10 40 42 am" src="https://cloud.githubusercontent.com/assets/1093738/13399400/1a375292-ded1-11e5-867f-fe6c9d382175.png">

**Comment by davidkpiano** [comment]
@sattaman Does this solve your issue?

**Comment by sattaman** [comment]
Hi, yes that explains why I was having issues.

To clarify, at present I had named my modal reducers names like:

`sms: createModelReducer("message.compose.sms")`

Am I right in thinking it's only going to work if I instead use names such as 

`composeSms: createModelReducer("composeSms")

Does the hierarchy of where the reducer is affect anything? For instance, if the reducer where my initial model was 'message.compose'? 
`

**Comment by sattaman** [comment]
I may have just spotted the answer in the other issues that was created, namely the nested state example. 

http://davidkpiano.github.io/react-redux-form/#/recipe/model-in-nested-state?_k=t4nbbq

**Comment by nickzarate** [comment]
@sattaman Is the example link you gave [here](http://esnextb.in/?gist=61d8891f6bb8e6a5009b), a working example? If so, why do you use `controls.text` instead of `controls.checkbox` if you are using an Input of type checkbox? The docs for [react-redux-form](http://davidkpiano.github.io/react-redux-form/#/api/Guide:-React-Native-&-Custom-Components?_k=qmlwwh) say that `controls` has a list of mappings, `text` is for text-based inputs and `checkbox` is for checkbox-based inputs. Does `controls.text` just happen to work for this instance or am I not understanding the docs correctly?

**Comment by sattaman** [comment]
@nickzarate It seemed to work , I don't think you can define more than one createFieldClass for the same input type, and putting them as text seemed to work. I initially had issues with the state path not matching the model.
