### ISSUE TITLE
How to get the right index for array model?

### ISSUE THREAD

**Issue by leesiongchan** [davidkpiano/react-redux-form#41]
```javascript
const users = [{ name: 'Brad Pitt' }, { name: 'Bruce Wayne' }];

// UserDetails.js
const UserDetails = ({ user }) => (
  <Field model="users[??].name">
    <input value={user.name} />
  </Field>
);
```

The question is how do I fill the index inside the `<Field model ... >` ??

**Comment by leesiongchan** [comment]
`userId` passing along to all the subcomponents seem to be little verbose. Do we have a better option?

**Comment by davidkpiano** [comment]
This might be a React/JavaScript question rather than a specific React-Redux-Form question. You need to somehow get the `index` of each user inside the `<UserDetails>` component.

Here's a couple of approaches:

```js
const users = ...;

const UserDetails = ({ user, index }) => (
  <Field model={`users[${index}].name`}>
    <input value={user.name} />
  </Field>
);
```

Or like this, in a `mapStateToProps` selector or otherwise:

```js
const users = [{ name: 'Brad Pitt' }, { name: 'Bruce Wayne' }];
const indexedUsers = users.map((user, index) => ({ ...user, index }));

// now if you use indexedUsers instead of users...

const UserDetails = ({ user }) => (
  <Field model={`users[${user.index}].name`}>
    <input value={user.name} />
  </Field>
);
```

So, there's a couple of approaches to this. Hope that helps!
