### ISSUE TITLE
mapProps leads to undefined props.value on a custom control

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#416]
Hi, 
great to see v1 is is already there! Thx. 👍 

Just created a custom control and figured out on v1.01 it do no longer pass the value to my custom component when mapProps is used. Here my simple example:
```jsx
class CustomInput extends Component {

    constructor(props) {
        super(props);
    }

    render() {
        console.log('value: ', this.props.value); // will be undefined when using in conjunction with mapProps
        return (
            <input type="text" {...this.props} />
        );
    }
};

// somewhere else
<Control
    model={'checkoutStart.test'}
    component={CustomInput}
    mapProps={{
        error: (props) => (!!props.errors), // any kind of mapProps
    }}
/>
```
If the ```<Control />``` do not have a mapProps prop it seems to work ...

**Comment by davidkpiano** [comment]
Just added the ability in fbe3ee8 to extend existing `mapProps` if you define your control like this:

```diff
-<Control
+<Control.text
    model={'checkoutStart.test'}
    component={CustomInput}
    mapProps={{
        error: (props) => (!!props.errors), // any kind of mapProps
    }}
/>
```

Otherwise, you have to explicitly map `{ value: (props) => props.viewValue }` in the props, and here's why (updated the docs with the below answer):

-----


One important thing to keep in mind is that there is no single `value` for a `<Control>`; rather, there are two types of values (that are equivalent, more often than not):

- `modelValue` - the exact value of the model in the store's state
- `viewValue` - the _displayed_ value of the model in the component's state

For example, if a text control has `updateOn="blur"`, its `viewValue` will represent what is being typed in the input, whereas the `modelValue` will represent the persisted value, once the input is blurred.

Because of this, you will want to map the `viewValue` to a custom control's `value` if you wish to externally update the value:

```jsx
const CustomInput = (props) => (
  <div className="custom-input">
    <input type="text" {...props} />
  </div>
);

const CustomInputControl = (props) => (
  <Control
    component={CustomInput}
    mapProps={{
      value: (props) => props.viewValue,
    }}
    {...props}
  />
);
```

Alternatively, you can just _assign_ existing mapped props to your custom control:

```jsx
// the prop mapping of Control.text is used below:
const CustomInputControl = (props) => (
  <Control.text component={CustomInput} />
);
```

**Comment by MiMaMuh** [comment]
Okay. Yes, I saw the two differences but I think my issue is, that the ```value``` is ```undefined``` even if I map it with mapProps like: ``` { value: (props) => props.modelValue } ```.  I logged the props within a map-function and saw ```modelValue``` is ```undefined```. 

I've set the initial-state for formReducer and modelReducer but ```props.modelValue``` in the mapProps-function is undefined.

In my case I want to accomplish two things:
1. Have an custom control which should display the ```modelValue``` initially. I tried to pass a initial-state to the modelReducer and the formReducer. This works when I use ```props.fieldValue.value``` within my mapProps-function but won't work with ```props.modelValue```?
Is it by design?

2. My custom control uses validators which seem to run after mount. The validation always fails even if I set a valid value with the initial-state. I'm not sure if this is by design ...

**Comment by davidkpiano** [comment]
What does your `store` look like?

**Comment by MiMaMuh** [comment]
Basically something like:
```js
const combinedReducer = combineReducers({
    myForm: modelReducer('example', {
        inputValue: '500.00',
    }),
    myModel: formReducer('example', {
       inputValue: '500.00',
    })
});

// ...
```

**Comment by davidkpiano** [comment]
```js
// ...
myForm: modelReducer('example', {
// ...
```

Make sure that the `model`, which is the first argument to `modelReducer`, is the _exact_ path to the model's state in the store. So in the above example, it should be `'myForm'` or whatever you named your model.

**Comment by MiMaMuh** [comment]
Thank you, that was my issue!
