### ISSUE TITLE
action.reset should reset to last actions.load

### ISSUE THREAD

**Issue by slashwhatever** [davidkpiano/react-redux-form#426]
Use case:

Form loaded with data via and ajax call.
User updates records in the form.
Clicks submit.
For reasons, the persist fails and the ajax call returns an error.

We now need to reset the form to the values present before the update action took place.

Currently, when I call `actions.reset()`, the form returns to a blank state.
Desired functionality; the form should reset to the state it was in when actions.load was last called. Either by default or by giving it an attribute to affect it's behaviour when reset is called.

Other frameworks I've used support this idea by having a attribute on the form itself (one in particular, for example, uses trackResetOnLoad: true/false. True resets to the last loaded model).

**Comment by davidkpiano** [comment]
Sure, I'll add this functionality. It makes sense.

**Comment by venelin-mihaylov** [comment]
I second that, I load data the same way. Currently, I store the loaded record at a separate place in the redux state and on reset I do actions.load(loadedRecord)

**Comment by dmzkrsk** [comment]
Is it working?
I have a form, which state is loaded via `action.load`, then I try to `action.reset` and my form is blank.

This commit refers only field reducer.

I checked properties of my fields, `modelValue` is undefined, but `fieldValue.initialValue` is correct. (I'm still a bit of confused about `modelValue` vs `fieldValue`)

**Comment by davidkpiano** [comment]
> This commit refers only field reducer.

Can you open a new issue if it doesn't work form-wide?

**Comment by jomasti** [comment]
Is this new change not optional?

**Comment by davidkpiano** [comment]
@jomasti What's your use case for not wanting to reset it to the initial state?

**Comment by jomasti** [comment]
Let's say I have a list of results after creating groups using the form. From that view, you can create a new group. It will take you to a blank form. You can hit cancel and go back to the list view. Also from the list, you are allowed to edit the saved group. You click edit, it will go to that same form and use actions.load to set the state for that saved form. When you hit cancel again to go back to the list, actions.reset is called. But now it isn't reset to the blank form like it previously was. So, I pretty much do want to go back to the initial initial state instead of the initial loaded one. I do see the benefit of that, though, so it makes sense for this to be optional.

**Comment by davidkpiano** [comment]
> You click edit, it will go to that same form and use actions.load to set the state for that saved form.

You can use `actions.change` - the use-case for `actions.load` is two-fold:
- wanting something to be the _new_ initial state of the model
- wanting to silently change the model

For most intents and purposes, `actions.change` will be the action you want to use. That way, you will get your expected behavior of having a blank form upon `actions.reset`.

**Comment by jomasti** [comment]
Oh, okay. That makes sense. Thank you!
