### ISSUE TITLE
Working with redux-saga

### ISSUE THREAD

**Issue by nasushkov** [davidkpiano/react-redux-form#460]
Hi
Is there any way to make react-redux-form work with redux-saga? I see that current actions implementation of actions is tightly coupled with redux-thunk approach to asynchronous workflow

**Comment by davidkpiano** [comment]
I've been using it with redux-saga in a production app - all you have to do is include the `thunk` middleware before passing the action onto redux-saga:

```js
// ...
import thunk from 'redux-thunk';
import createSagaMiddleware from 'redux-saga';
// ...

const sagaMiddleware = createSagaMiddleware();

const store = createStore(combineForms({
  // ...
}, applyMiddleware(sagaMiddleware, thunk));
```

Does that work with your use case?

**Comment by nasushkov** [comment]
Thank you for your answer, David.  Well, yes, we can do this by combining both libraries, of course, and that's the easiest solution, but for me it's a little bit inconvenient, since redux-thunk and redux-saga serve the same purpose and I prefer redux-saga for several reasons. So, in this case I had to use both libraries just because of react-redux-form. I can reformulate my question: can we use redux-saga instead of redux-thunk with react-redux-form? For instance, I see that thunks are used in several actions based on `submit` action, so would it be enough to rewrite these actions as sagas to make it work without redux-thunk?

**Comment by davidkpiano** [comment]
I think this would be best as a separate package, like `rrf-saga` or something like that. My thinking is that RRF tries to serve as the lowest common denominator for most React + Redux projects, and I don't want to add extra compatibility integrations such as for redux-saga, redux-observable, etc. etc. because that is beyond the scope of this package.

I'm also planning on removing the requirement for `redux-thunk` by refactoring many of the actions used internally by components such as `<Field>`, `<Control>`, etc. My original plan was to "require" `redux-thunk` only as a convenience for directly dispatching the actions yourself.

As for right now, I'd strongly recommend using both `redux-thunk` and `redux-saga` as they are both middlewares, and redux idiomatically allows multiple middlewares. The usage of `redux-thunk` should just be considered an implementation detail.
