### ISSUE TITLE
Unknown Props on Custom Input

### ISSUE THREAD

**Issue by DanielLuu** [davidkpiano/react-redux-form#475]
```
const CustText = (props) => (
  <div className={`form-group ${(props.valid === false && props.touched === true) ? 'has-error' : ''}`}>
    <label className="control-label">{props.label}</label>
    <input className="form-control" {...props}/>
    <Errors className="error" model={props.name} show={props.touched}
      messages={{required: 'Required'}}/>
  </div>
);
```

`mapProps={{valid: ({fieldValue}) => fieldValue.valid, touched: ({fieldValue}) => fieldValue.touched}}`

Getting a
```
warning.js:36 Warning: Unknown props `valid`, `touched` on <input> tag. Remove these props from the element.
```

**Comment by davidkpiano** [comment]
This is because you are passing in all the props here:

```jsx
<input className="form-control" {...props}/>
```

Try to pass in only the props you need into that component, such as `onChange={props.onChange}`. You can also use Lodash's `omit` or `pluck` functions to help you out in whitelisting/blacklisting props.

I'd recommend against blindly passing in all the props - that is, avoid this pattern: `<div {...props}>`.

**Comment by DanielLuu** [comment]
Thanks for the fast answer!
