### ISSUE TITLE
array field not work

### ISSUE THREAD

**Issue by Maxim-Chugaev** [davidkpiano/react-redux-form#486]
1.0.12
```javascript
<Field model="model.some_fields[0]">
   <input type="text"/>
</Field>
<Field model="model.some_fields[1]">
   <input type="text"/>
</Field>
<Field model="model.some_fields[2]">
   <input type="text" />
</Field>
```
in form 
```javascript
some_fields: {
  '$form': { initialValue: [...], ... }
}
```
but earlier in 1.0.9
```javascript
some_fields: {
 $form: {...},
 '0': {touched... etc},
 '1': {touched... etc},
 '2': {touched... etc},
}
```
i am not sure, but old behavior be correctly.

**Comment by davidkpiano** [comment]
I think RRF is behaving correctly, in this case.

When you add `<Field>` or `<Control>` components with models that _do not exist on the store_, then they will only be instantiated on load if there is a `defaultValue` on the field.

Otherwise, RRF will be **lazy** and not create the field until it is interacted with.

My recommendation would be to define `model.someFields = []` in your store (in `combineForms()`, etc.). Let me know if this works with your use case.
