### ISSUE TITLE
componentWillUnmount issue

### ISSUE THREAD

**Issue by dave-clover** [davidkpiano/react-redux-form#580]
Hello again,

Users have been reporting some issues when trying to submit their forms.  I'm basically on the other side of this issue: #346.  I was previously relying on `componentWillUnmount` to reset all the validators when the control unmounts (not just the validators explicitly added to the field).  In general, the change in #346 makes sense.  However, I'm hitting an issue.

I have some validation rules that have been not explicitly added to the control component.  Specifically, `setValidity` gets called in an action when another field changes.  It's a bit more complicated than that, but I'm trying to simplify here.

Basically the issue is that React doesn't pass in updated props before calling `componentWillUnmount`, so when `dispatch(actions.setValidity(model, omit(fieldValue.validity, keys)));` is called in control-component.js, it's essentially adding validation rules that were just removed back, causing the form to stay invalid.

The flow is something like:

1. I have two validation rules, `foo` and `bar`.  `foo` has been explicitly added to the control.  `bar` has not.  Both are invalid.
2. I click a button to remove a section of the form (where this control I mentioned lives).  This is done in an action.
3. In the same action, I call `resetValidity` on the control.
4. The component immediately calls `componentWillUnmount()`, but since React does not pass in new props before unmounting, `bar` comes back as invalid.

I'm about to submit a PR that disables the unmounting behavior, but I'm wondering if you have a better solution.

**Comment by davidkpiano** [comment]
Hmm, if I understand the problem correctly, the issue lies in taking the existing validity, and _setting_ the validity (with own validator keys removed) on unmount, even if that validity is "stale". 

I'd like to approach this by instead doing something like this:

```diff
-dispatch(actions.setValidity(model, omit(fieldValue.validity, keys)));
+dispatch(actions.resetValidity(model, keys));
```

and then modify the reducer/action so that instead of setting it to the stale validity without `keys`, it _only resets_ the specified keys, so other parts of the validity are untouched - in this case, the other validity is gone anyway, and will remain that way.

**Comment by dave-clover** [comment]
Sounds good.  I'll get started.
