### ISSUE TITLE
Validation skipped when user presses the "Enter" button.

### ISSUE THREAD

**Issue by hgylfason** [davidkpiano/react-redux-form#777]
### The Problem
A user can submit a form by pressing "Enter". This is a problem (for me at least) because the fields are validated on "blur" and that validation is skipped when the "enter" button is used.

### Steps to Reproduce
1. Go to the codepen example
2. Write something in the first name field and then in the last name field.
3. Now both fields should be valid. Empty the first name field and keep the focus on that field.
4. Push enter and see that the form is submitted even though the form wasn't valid.

### Expected Behavior
I expected that a validation would occur on the submit event and the form wouldn't be submitted.

### Actual Behavior
The form is submitted.

### Reproducible Code Example
http://codepen.io/hgylfason/pen/VbyLPY?editors=0010#0

### Also
I realise that this "bug" is possibly intended behaviour.
If so then what is the recommended way to validate the form for this case i.e. where the user submits via keypress and validation is done on blur/focus?

**Comment by davidkpiano** [comment]
Seems like something that should be fixed. I suspect the sequence of events right now is:

- Form is submitted
- Field is blurred (by this point it's too late)

so I'd have to add some logic that triggers validation on fields before submit... which can be really tricky if we take async validation into account as well.

**Comment by cipater** [comment]
I think bc4b9b98c50bac022652f8e7d2aaf2515097134c may have introduced a bug for my use-case:

I have a Custom control that takes an attribute indicating the value should be treated as an Integer... This wraps rrf's ```onChange``` function, calling ```parseInt``` on the value before passing it down.

This works fine when the form is submitted via a button click. However, if this custom control has focus when <kbd>enter</kbd> is pressed, it appears to be pulling the String value directly from the input, rather than the value stored in the ```$form``` object. 

Given:
```
<LocalForm onUpdate={ form => console.log(form) }>
  <CustomInput type='number' model='.number' />
</LocalForm>
```

On pressing <kbd>enter</kbd> I get 3 console entries; the first shows ```$form.number.value```  as being an Integer, the next two are both Strings, which is ultimately what the ```onSubmit``` handler receives.

I don't quite see in this commit how the String value would get reincorporated into the ```$form``` object. So maybe it's something else... The ```forcedUpdate ? value : modelValue``` ternary led me here.

**Comment by davidkpiano** [comment]
Can you open a separate issue for that so that it doesn't get lost, @cipater ?
