### ISSUE TITLE
Errors helper/utility

### ISSUE THREAD

**Issue by varzock** [davidkpiano/react-redux-form#778]
Hello,

First of all, thank you for the great library! I was comparing this and Redux Form for a long time and I am happy I chose this in the end.

I don't know if this feature is hidden somewhere in the utils but I am in serious need of a utility/helper/selector that gives me all the errors on the model (after submit) which are in the same order as presented on the DOM.

The reason behind this is that I have a long form and when the form submit fails, I need to scroll the view on the first error on the form and right now I haven't found a built-in solution for this so I am currently comparing DOM elements and their positions and based on these values I select one element and scroll the view onto that.

The best solution would be to be able to give an error class as a prop on the Form/LocalForm component which would then add that class to all Control-components when submit fails. This way I could use getElementsByClassName and get the first element and scroll/focus on it.

Hope my problem makes some sense.

**Comment by davidkpiano** [comment]
I don't think this should be handled by the library, especially since it's a very specific use-case and non-trivial. However, you can [add class names based on field state](http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html#how-do-you-add-conditional-class-names-based-on-field-state) pretty easily:

```jsx
<Control.text
  model="user.firstName"
  mapProps={{
    className: ({fieldValue}) => !fieldValue.valid
      ? 'invalid'
      : ''
  }}
/>
```

Let me know if that helps.
