### ISSUE TITLE
Object.keys: argument is not an Object (IE11)

### ISSUE THREAD

**Issue by varzock** [davidkpiano/react-redux-form#806]
### The Problem
Validation on Internet Exploder (sic) 11 causes error: `Object.keys: argument is not an Object`

### Steps to Reproduce
For example with LocalForm. Same problem occurs with Form as well. Create Form with validations object on the form. Focus on field, check console.log and you'll see the error message. OnChange triggers it.

Error seems to be caused by line 364 in form-actions-reducer.js.

### Expected Behavior
No errors on IE11.

### Actual Behavior
On Internet Explorer 11: `Object.keys: argument is not an Object`
Other browsers seem to be fine.

### Reproducible Code Example
```
<LocalForm
    model="user"
    noValidate
    validators={{
        firstName: {
            isRequired: (value) => value && value.length,
        }
    }}
>
    <Control.text
        model=".firstName"
    />
</LocalForm>
```

Sorry, couldn't get the CodePen fork working.

**Comment by hitchcockwill** [comment]
@davidkpiano I'm still experiencing this same issue on IE11 after the 1.12.0 update. I'm seeing this with almost an identical config to the one above only on the <Form> component rather than LocalForm.

Inputs are set up to validateOn="change" and there is a 300ms debounce as well.

The stack trace points to the updateParentsForms function. I can try to put together some more detailed tests later.

**Comment by davidkpiano** [comment]
Please do, currently nothing in `updateParentForms` should call `Object.keys`.

**Comment by Kikketer** [comment]
Thanks @hitchcockwill I was running into the same issue using a combination of 'create-react-app' and had to simply add es6-shim to the polyfills.

**Comment by AmbiTews** [comment]
I am getting error Object.keys: argument is not an Object , I have IE version 11.1805.15063.0
