### ISSUE TITLE
Setting the "value" mapProps moves the cursor to the end

### ISSUE THREAD

**Issue by ozgor** [davidkpiano/react-redux-form#885]
### The Problem

Setting a "value" mapProps moves the cursor to the last position when you enter a new character, instead of staying in the same position.

### Steps to Reproduce

Create a textarea

```
<Control.textarea
    model="path.to.your.model"
/>
```

write something inside (.e.g. "abcd")
move the cursor at the beginning of the line (click before the first letter, "a")
enter "e"
=> you get "eabcd" and the cursor is at the index 1

Now try again by setting the "value" mapProps

```
<Control.textarea
    model="path.to.your.model"
    mapProps={{
        'value': ({ modelValue }) => modelValue
    }}
/>
```

The cursor goes back to the last position

### Expected Behavior

cursor should be at index 1

### Actual Behavior

cursor is at index 5

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa))

**Comment by davidkpiano** [comment]
Any reason you're mapping the prop in the first place? The behavior you're trying to map already should work.

**Comment by ozgor** [comment]
yes, I need to transform the value based on the value (not implemented in my example here as this is not related to the issue)

**Comment by davidkpiano** [comment]
Hmm... if you don't use RRF at all, can you make a custom component that does exactly the behavior you want without the cursor jumping? Might not be (just) an RRF issue.

**Comment by davidkpiano** [comment]
Okay, solution: you want to use `viewValue` for the mapping, not `modelValue`, and there's a good reason why.

In an RRF input, when you change a value, two things happen in a specific order:
1. The `viewValue` (which is in the control's internal state) is set.
2. The `modelValue` is changed (via dispatching an action)

That way, if the `modelValue` is updated externally, the component checks if the `viewValue` is out of sync, and updates it. In this case, it doesn't matter where the cursor is since the update is external.

However, if you map the `value` to the `modelValue`, then step 1 is _skipped_ (since you're manually setting `value` to the `modelValue` and controlling it yourself), and now RRF has to sync the `viewValue` again, even if it's not an external change. 

So `mapProps={{ value: ({ viewValue }) => viewValue }}` is your best bet, but I'd really like to know what kind of value transformation you're doing, because I can help you find a better way to do it.
