### ISSUE TITLE
Do we support dependent fields?

### ISSUE THREAD

**Issue by khanghoang** [davidkpiano/react-redux-form#9]
Hi, Thank you, this is very useful library. 

I have a question that is there any example about dependent fields, let's say I have `country` and `cities` dropdown field, the `cities` field depends on the `country`'s. How can we handle that case?

If we don't have it now but you plan to have it, let me know, I really want to help.

**Comment by luisrudge** [comment]
What do you want to do with that? I mean.. you can just react to the `onChange` method of `country` and fetch your cities.

**Comment by khanghoang** [comment]
Ya, you're right. I overthink it.

I will open it again when there is a good circumstance

**Comment by davidkpiano** [comment]
Thanks for the question, @khanghoang. Yep, since RRF just deals with plain JS object/array models, you can just conditionally render the list of cities based on the chosen country. For instance, if you have a `<Field model="address.country">` you can just have a custom function that renders the correct cities and call it in a map: `{ getCities(address.country).map(city => ...) }`
