### ISSUE TITLE
actions.change() and modelValue-field binding

### ISSUE THREAD

**Issue by jekamoroz** [davidkpiano/react-redux-form#97]
I think would be good to have some kind of binding between model value in store and field value.

The problem:
I dispatch `actions.change('model.foo', 'bar')`, and actually what only happens is changing in store, in model reducer, but probably value in e.g. input field should be then also updated?

**Comment by davidkpiano** [comment]
If you are implementing the `<Field>` component, keep in mind that your components will be uncontrolled components. More on that here: https://facebook.github.io/react/docs/forms.html#controlled-components

**Why?** This is to allow for changes to occur at any time; e.g. on blur, debounced, etc.

**How to bind:**
Simply pass in the value in your connected component:

```js
<Field model="user.email">
  <input type="text" value={ user.email } />
</Field>
```

In the future, I might think about having components be controlled, in that they are in sync with a `viewValue` rather than the `value`, but that may cause performance issues (actions occurring every single change, etc.)

**Comment by davidkpiano** [comment]
I added this to the [FAQs](https://davidkpiano.gitbooks.io/react-redux-form/content/faqs.html) for now. If anything is going to come from this, it might be something like a `<Field controlled={true}>` prop, but not likely.
