### ISSUE TITLE
Model changed before submit.

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#977]
### The Problem
```
changeAndSubmit = (model, value) => {
    return (dispatch) => {
      dispatch(actions.change(model, value));
      dispatch(actions.submit('model', this.submitPromise));
    };
};
```

this.submitPromise - have not changed model from dispatch(actions.change(model, value));

Do you have any variant of 
dispatch(actions.change(model, value)).then() 

To be sure that model is changed before submit?

**Comment by davidkpiano** [comment]
Unfortunately, because of the Redux model where it is difficult to chain sequences of actions that are "reactive" to state changes, you have to do something like this:

```js
dispatch(actions.change(model, value));
setTimeout(() => dispatch(actions.submit(model, this.submitPromise)), 0);
```

Let me know if this works for you. It's otherwise tricky because both actions execute with regard to the state being the same, even if the first action changes the state on the next tick. So the above workaround waits til that next tick.
